### PR TITLE
[ETFE-2933] Read from UserAnswers, if no data, then read from IE801

### PR DESCRIPTION
**Pull request by MJCallahanPage**
**IMPORTANT**
- I've raised this as a `DRAFT` just for visibility really. It's not near being ready to be raised and merged properly yet.
- Someone else needs to pick this up? Would recommend @james-work-account probably as I `git chery-picked` most of the changes from his branch. Then refactored bits.
- The code compiles and runs. The flow is currently nonsense as the `INFO` section will be re-puprosed to ask the CoD upfront questions. But there's a flow that to mimick completing that and then landing on the Task List page
- The task list page has logic to work out if a `ReviewPage` has been answered for each section. Those pages don't exist yet, but will be built as part of future stories.
- The task list renders the sections - but the logic around what sections should render has NOT been checked or changed yet. That again needs to be done in future stories
- When you click into a section, it currently goes to the CYA and shows you all the answers for that section. Those values are either from the IE801 or the saved draft answers depending on whether you change and save anything amendments.
- The Unit Tests COMPILE but DO NOT RUN. There's a lot of tests which check something like "IF there's no data THEN do not show." but these tests do now return data because it falls back on the IE801 response. So all of those tests need updating and any other failing tests reviewed. It took me ages to rebase, refactor and update the code and tests so didn't get time to go through the failing tests unfortunately.

### CODE REVIEW

**Comment by LewisMitchell** [comment]
Spotted a bug on the Transport Units section. When the user tries to add more transport units (when there is already existing TU's in 801) then the FE returns an error because the 801 TU state is not reflected in the user answers.

Solution implemented: when the user hits the index page for TU and they have no existing TU's in their local user answers, then copy all the TU's from 801

**Review by MJCallahanPage — COMMENTED** [review]
I can't approve this as I raised it; but I've checked the changes Lewis has added and they LGTM.

I think we could get this in as it is and then forward fix anything else as part of the future CoD stories.

**Comment by james-work-account** [comment]
I'll double check it against my PTs and the JTs then re-review

**Review by james-work-account — CHANGES_REQUESTED** [review]
1. Missing Transport Units CYA - is this intentional?
2. /trader/ern/**draft**/:arc/destination/check-answers -> /trader/ern/**movement**/:arc/destination/check-answers
3. We could do with softening the validation on Declaration and doing a dummy Submit for now; currently it's looking for pages which don't exist and is trying to submit something which is missing mandatory answers. This will be hooked up properly later so it's probably worth just relaxing the requirement to hit Declaration and removing the "create a model and submit" bits from Submit

**Review by james-work-account — APPROVED** [review]

**Pull request merged**
